# Generated by Django 4.1.7 on 2023-03-23 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2023, 3, 23, 21, 35, 57, 963462, tzinfo=datetime.timezone.utc)),
        ),
    ]
