# Generated by Django 4.1.7 on 2023-04-05 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author_alter_post_date_posted_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 22, 27, 49, 491474, tzinfo=datetime.timezone.utc)),
        ),
    ]
