# Generated by Django 4.1.7 on 2023-04-24 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2023, 4, 24, 14, 43, 10, 212547, tzinfo=datetime.timezone.utc)),
        ),
    ]
