# Generated by Django 4.1.7 on 2023-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=35)),
                ('body', models.TextField(max_length=500)),
                ('media_img', models.ImageField(height_field='145px', upload_to='', width_field='145px')),
                ('media_video', models.FileField(upload_to='')),
            ],
        ),
    ]
